### PR TITLE
Fix #31 - Lower minSDK

### LINKED ISSUE #31: Question: minSDK
Any reason why this library's minSDK is so high? Currently is at `15`

### PR DESCRIPTION
**Pull request by eyedol**
This aims to answer question asked in #31 - If that is not the case, feel free to close this `PR` without merging.
Changes here include:
- Update android-spock to latest. This allows us to support minSDK 8 and above
- Lowered to minSDK to 8
- ~~Bump version number~~

### CODE REVIEW

**Comment by Gi-lo** [comment]
@eyedol The project does not compile against ```compileSdkVersion 8```. This is because [apply()](http://developer.android.com/reference/android/content/SharedPreferences.Editor.html#apply()) is only available since api level 9. I do not want to use commit as it may block the main thread. Instead I suggest dropping api level 8 and supporting 9 instead? What do you think?

**Comment by eyedol** [comment]
Good catch. Since `apply` is only used in `SharedPreferencesOAuth2AccessTokenStorage` (right ?) we could use an interface to provide different implementation. Make implementation for `apply` and `commit`. I don't know how that will affect `spock` though. If it's going to cause much issue, then I'll bump it to `9` otherwise I'll provide a fix for that. Let me know.

**Comment by Gi-lo** [comment]
Well, according to [this chart](https://developer.android.com/about/dashboards/index.html?utm_source=suzunone), I think that we can and should drop api level 8 and support everything starting from 9.

**Comment by eyedol** [comment]
Okay. Bumped to minSDK `9`

**Comment by Gi-lo** [comment]
:+1:

**Pull request merged**
